-- Complete core data for all European countries (Stats & Comparisons, dashboard cards).
-- SOURCES (same for all): GDP = World Bank (current US$, 2022). Height = NCD-RisC / national stats.
-- Religion = CIA World Factbook. Pros/cons = community-curated, consistent tone.
-- Run in Supabase SQL Editor after Countries table exists. Updates by slug.

UPDATE "Countries" SET reddit_pros = 'Affordable by Western standards. Lisbon and Porto have good nightlife. Latin culture, friendly people.', reddit_cons = 'Dating scene can feel small. Many locals leave for work abroad. Tourism saturation in hotspots.', avg_height_male = '174 cm', avg_height_female = '161 cm', gdp_per_capita = '~$27,500', majority_religion = 'Catholic' WHERE slug = 'portugal';
UPDATE "Countries" SET reddit_pros = 'English widely spoken. Direct culture, no games. Good infrastructure and safety.', reddit_cons = 'Very feminist, Western dating norms. Expensive. Dutch women often not interested in foreign dating.', avg_height_male = '184 cm', avg_height_female = '170 cm', gdp_per_capita = '~$58,000', majority_religion = 'Non-religious / Christian' WHERE slug = 'netherlands';
UPDATE "Countries" SET reddit_pros = 'Multilingual (French, Dutch, English in Brussels). Central location. Good beer and food.', reddit_cons = 'Split culture (Flemish/Walloon). Dating scene similar to France/Netherlands. Not a PPB destination.', avg_height_male = '182 cm', avg_height_female = '168 cm', gdp_per_capita = '~$52,000', majority_religion = 'Catholic' WHERE slug = 'belgium';
UPDATE "Countries" SET reddit_pros = 'Safe, clean, beautiful Alps. Vienna has culture and nightlife.', reddit_cons = 'Reserved culture. Expensive. Austrian women similar to German—cold approach rarely works.', avg_height_male = '179 cm', avg_height_female = '166 cm', gdp_per_capita = '~$52,000', majority_religion = 'Catholic' WHERE slug = 'austria';
UPDATE "Countries" SET reddit_pros = 'Wealthy, safe, stunning nature. Multilingual.', reddit_cons = 'Extremely expensive. Reserved culture. Small dating pool. Not PPB-friendly.', avg_height_male = '179 cm', avg_height_female = '164 cm', gdp_per_capita = '~$92,000', majority_religion = 'Christian' WHERE slug = 'switzerland';
UPDATE "Countries" SET reddit_pros = 'Wealthy, safe, beautiful. High English proficiency.', reddit_cons = 'Very expensive. Reserved Nordic culture. Feminist norms. Cold approach frowned upon.', avg_height_male = '182 cm', avg_height_female = '168 cm', gdp_per_capita = '~$89,000', majority_religion = 'Christian' WHERE slug = 'norway';
UPDATE "Countries" SET reddit_pros = 'Happy society, good English. Copenhagen has nightlife.', reddit_cons = 'Expensive. Nordic reserve. Similar to Sweden/Norway for dating.', avg_height_male = '182 cm', avg_height_female = '169 cm', gdp_per_capita = '~$68,000', majority_religion = 'Christian' WHERE slug = 'denmark';
UPDATE "Countries" SET reddit_pros = 'Safe, educated, good English. Sauna culture.', reddit_cons = 'Very reserved. Expensive. Dating culture similar to other Nordics.', avg_height_male = '180 cm', avg_height_female = '166 cm', gdp_per_capita = '~$54,000', majority_religion = 'Christian' WHERE slug = 'finland';
UPDATE "Countries" SET reddit_pros = 'Friendly people, English-speaking. Dublin has nightlife and tech scene.', reddit_cons = 'Expensive. Weather. Dating culture similar to UK—Western, feminist norms.', avg_height_male = '179 cm', avg_height_female = '164 cm', gdp_per_capita = '~$85,000', majority_religion = 'Catholic' WHERE slug = 'ireland';
UPDATE "Countries" SET reddit_pros = 'Beautiful, Mediterranean culture. Athens and islands have nightlife. More traditional than North Europe.', reddit_cons = 'Economic instability. Greek women can be family-focused; marriage expectations. Tourist saturation in islands.', avg_height_male = '178 cm', avg_height_female = '165 cm', gdp_per_capita = '~$22,000', majority_religion = 'Orthodox' WHERE slug = 'greece';
UPDATE "Countries" SET reddit_pros = 'Prague is beautiful and (still) relatively affordable. Good beer, architecture. Central European vibe.', reddit_cons = 'Formerly a paradise—now more Westernized. Czech women can be cold. Tourism has changed the scene.', avg_height_male = '181 cm', avg_height_female = '168 cm', gdp_per_capita = '~$28,000', majority_religion = 'Non-religious' WHERE slug = 'czech-republic';
UPDATE "Countries" SET reddit_pros = 'Budapest is beautiful and (still) cheap. Thermal baths, nightlife. Hungarian women can be feminine.', reddit_cons = 'Language barrier. Nationalist vibe. Dating scene small for foreigners outside Budapest.', avg_height_male = '176 cm', avg_height_female = '164 cm', gdp_per_capita = '~$19,000', majority_religion = 'Catholic / Christian' WHERE slug = 'hungary';
UPDATE "Countries" SET reddit_pros = 'Coast and islands beautiful. Dubrovnik, Split, Zagreb. Mediterranean feel, more traditional than EU West.', reddit_cons = 'Tourist-heavy in season. Smaller economy. Croatian women often family-oriented.', avg_height_male = '181 cm', avg_height_female = '167 cm', gdp_per_capita = '~$19,000', majority_religion = 'Catholic' WHERE slug = 'croatia';
UPDATE "Countries" SET reddit_pros = 'Belgrade nightlife is famous. Affordable. Serbian women often traditional and feminine.', reddit_cons = 'Lower GDP, infrastructure gaps. Nationalist undertones. Not in EU.', avg_height_male = '182 cm', avg_height_female = '168 cm', gdp_per_capita = '~$9,500', majority_religion = 'Orthodox' WHERE slug = 'serbia';
UPDATE "Countries" SET reddit_pros = 'Cheapest in EU. Sofia and coast. Bulgarian women often beautiful, traditional.', reddit_cons = 'Corruption, weak institutions. Brain drain. Dating pool smaller.', avg_height_male = '178 cm', avg_height_female = '165 cm', gdp_per_capita = '~$14,000', majority_religion = 'Orthodox' WHERE slug = 'bulgaria';
UPDATE "Countries" SET reddit_pros = 'Bratislava close to Vienna. Affordable. Nature and castles.', reddit_cons = 'Smaller scene. Slovak women can be reserved. Less international than Czech.', avg_height_male = '181 cm', avg_height_female = '167 cm', gdp_per_capita = '~$23,000', majority_religion = 'Catholic' WHERE slug = 'slovakia';
UPDATE "Countries" SET reddit_pros = 'Vilnius is underrated. Baltic beauty, affordable. Good English among young.', reddit_cons = 'Small population. Cold winters. Dating pool limited.', avg_height_male = '181 cm', avg_height_female = '168 cm', gdp_per_capita = '~$26,000', majority_religion = 'Catholic' WHERE slug = 'lithuania';
UPDATE "Countries" SET reddit_pros = 'Riga has charm. Affordable. Baltic mix of cultures.', reddit_cons = 'Small population. Emigration. Russian influence. Limited scene.', avg_height_male = '181 cm', avg_height_female = '169 cm', gdp_per_capita = '~$21,000', majority_religion = 'Christian' WHERE slug = 'latvia';
UPDATE "Countries" SET reddit_pros = 'Digital nation, Tallinn beautiful. Good English. Nordic-Baltic mix.', reddit_cons = 'Small population. Reserved. Many blonde women but cold approach difficult.', avg_height_male = '182 cm', avg_height_female = '168 cm', gdp_per_capita = '~$28,000', majority_religion = 'Non-religious' WHERE slug = 'estonia';
UPDATE "Countries" SET reddit_pros = 'Safe, green, Ljubljana is lovely. Good standard of living. Alpine and Adriatic.', reddit_cons = 'Small country, small scene. Slovenes can be reserved. Not a classic PPB destination.', avg_height_male = '181 cm', avg_height_female = '167 cm', gdp_per_capita = '~$32,000', majority_religion = 'Catholic' WHERE slug = 'slovenia';
UPDATE "Countries" SET reddit_pros = 'Wealthy, safe, multilingual. EU hub.', reddit_cons = 'Tiny population. Very expensive. Expat bubble. Not a dating destination.', avg_height_male = '180 cm', avg_height_female = '166 cm', gdp_per_capita = '~$128,000', majority_religion = 'Christian' WHERE slug = 'luxembourg';
UPDATE "Countries" SET reddit_pros = 'English official. Mediterranean, EU. Warm weather.', reddit_cons = 'Small island, small pool. Expensive for size. Dating scene limited.', avg_height_male = '175 cm', avg_height_female = '163 cm', gdp_per_capita = '~$34,000', majority_religion = 'Catholic' WHERE slug = 'malta';
UPDATE "Countries" SET reddit_pros = 'Mediterranean, EU. Greek and Turkish mix. Beaches, history.', reddit_cons = 'Split island (North/South). Small population. Tourism-dependent.', avg_height_male = '178 cm', avg_height_female = '165 cm', gdp_per_capita = '~$32,000', majority_religion = 'Orthodox' WHERE slug = 'cyprus';
UPDATE "Countries" SET reddit_pros = 'Stunning nature. Safe. High equality, educated women.', reddit_cons = 'Tiny population. Very expensive. Everyone knows everyone. Not PPB.', avg_height_male = '181 cm', avg_height_female = '168 cm', gdp_per_capita = '~$73,000', majority_religion = 'Christian' WHERE slug = 'iceland';
UPDATE "Countries" SET reddit_pros = 'Beautiful coast, affordable. Budva nightlife. Less crowded than Croatia.', reddit_cons = 'Small country. Tourism seasonal. Limited infrastructure.', avg_height_male = '183 cm', avg_height_female = '170 cm', gdp_per_capita = '~$10,500', majority_religion = 'Orthodox' WHERE slug = 'montenegro';
UPDATE "Countries" SET reddit_pros = 'Very affordable. Ohrid and Skopje. Slavic-Mediterranean mix.', reddit_cons = 'Small economy. Brain drain. Less developed. Dating scene small.', avg_height_male = '176 cm', avg_height_female = '163 cm', gdp_per_capita = '~$7,000', majority_religion = 'Orthodox' WHERE slug = 'north-macedonia';
UPDATE "Countries" SET reddit_pros = 'Very affordable. Beaches, mountains. Albanian women often traditional. Emerging destination.', reddit_cons = 'Infrastructure still developing. Language barrier. Small expat community.', avg_height_male = '176 cm', avg_height_female = '164 cm', gdp_per_capita = '~$6,800', majority_religion = 'Islam' WHERE slug = 'albania';
UPDATE "Countries" SET reddit_pros = 'Sarajevo has character. Affordable. Mix of cultures.', reddit_cons = 'Post-war legacy. Complex politics. Emigration. Small scene.', avg_height_male = '182 cm', avg_height_female = '167 cm', gdp_per_capita = '~$7,500', majority_religion = 'Islam' WHERE slug = 'bosnia-and-herzegovina';
UPDATE "Countries" SET reddit_pros = 'One of Europe''s poorest—very affordable. Wine country. Traditional society.', reddit_cons = 'Mass emigration. Russian influence. Weak economy. Not in EU.', avg_height_male = '175 cm', avg_height_female = '162 cm', gdp_per_capita = '~$5,800', majority_religion = 'Orthodox' WHERE slug = 'moldova';
