/**
 * Average adult BMI by country, separated by gender (kg/m²).
 * Sources: WHO Global Health Observatory, NCD-RisC 2024, CDC/NCHS.
 * US reference: Male ~29.1, Female ~29.3 (CDC/NCHS).
 */
export const US_BMI = { male: 29.1, female: 29.3 } as const;

export type BmiByGender = { male: number; female: number };

export const COUNTRY_BMI: Record<string, BmiByGender> = {
  "philippines":          { male: 23.5, female: 24.1 },
  "thailand":             { male: 24.0, female: 25.2 },
  "indonesia":            { male: 22.7, female: 24.0 },
  "malaysia":             { male: 25.3, female: 26.0 },
  "vietnam":              { male: 21.9, female: 22.3 },
  "cambodia":             { male: 21.8, female: 23.0 },
  "japan":                { male: 23.8, female: 21.6 },
  "south-korea":          { male: 25.0, female: 23.3 },
  "china":                { male: 24.5, female: 23.8 },
  "india":                { male: 22.0, female: 22.7 },
  "pakistan":              { male: 23.5, female: 24.6 },
  "sri-lanka":            { male: 22.1, female: 24.0 },
  "laos":                 { male: 21.6, female: 22.8 },
  "taiwan":               { male: 24.8, female: 22.7 },
  "colombia":             { male: 26.0, female: 27.4 },
  "brazil":               { male: 26.5, female: 27.3 },
  "mexico":               { male: 28.0, female: 29.2 },
  "argentina":            { male: 27.5, female: 27.8 },
  "peru":                 { male: 25.9, female: 27.0 },
  "chile":                { male: 27.8, female: 28.5 },
  "venezuela":            { male: 26.5, female: 28.2 },
  "bolivia":              { male: 25.0, female: 27.2 },
  "ecuador":              { male: 26.0, female: 27.4 },
  "paraguay":             { male: 25.8, female: 27.0 },
  "uruguay":              { male: 27.0, female: 27.8 },
  "costa-rica":           { male: 27.0, female: 28.0 },
  "panama":               { male: 27.0, female: 28.5 },
  "dominican-republic":   { male: 26.8, female: 28.4 },
  "guatemala":            { male: 25.6, female: 27.8 },
  "usa":                  { male: 29.1, female: 29.3 },
  "canada":               { male: 27.5, female: 26.8 },
  "uk":                   { male: 27.4, female: 27.2 },
  "france":               { male: 25.6, female: 24.5 },
  "germany":              { male: 27.2, female: 25.7 },
  "spain":                { male: 26.8, female: 25.2 },
  "italy":                { male: 26.2, female: 24.6 },
  "portugal":             { male: 26.5, female: 25.8 },
  "poland":               { male: 27.3, female: 26.2 },
  "romania":              { male: 26.6, female: 25.5 },
  "hungary":              { male: 27.8, female: 26.8 },
  "czech-republic":       { male: 27.5, female: 25.8 },
  "bulgaria":             { male: 26.6, female: 25.4 },
  "greece":               { male: 27.5, female: 25.8 },
  "turkey":               { male: 27.0, female: 28.8 },
  "serbia":               { male: 27.0, female: 25.8 },
  "croatia":              { male: 27.0, female: 25.6 },
  "albania":              { male: 26.2, female: 26.0 },
  "north-macedonia":      { male: 26.4, female: 26.2 },
  "montenegro":           { male: 26.8, female: 25.6 },
  "estonia":              { male: 26.8, female: 25.4 },
  "sweden":               { male: 26.2, female: 24.8 },
  "russia":               { male: 26.0, female: 27.6 },
  "ukraine":              { male: 26.2, female: 27.4 },
  "kazakhstan":           { male: 26.0, female: 27.0 },
  "georgia":              { male: 26.4, female: 26.6 },
  "egypt":                { male: 27.5, female: 30.3 },
  "morocco":              { male: 24.8, female: 27.6 },
  "algeria":              { male: 25.0, female: 27.8 },
  "tunisia":              { male: 25.8, female: 28.2 },
  "libya":                { male: 27.0, female: 28.8 },
  "saudi-arabia":         { male: 28.5, female: 30.2 },
  "united-arab-emirates": { male: 27.6, female: 29.0 },
  "iran":                 { male: 25.8, female: 28.0 },
  "kenya":                { male: 22.0, female: 24.8 },
  "nigeria":              { male: 22.5, female: 24.6 },
  "south-africa":         { male: 24.5, female: 30.5 },
  "tanzania":             { male: 21.8, female: 24.2 },
  "uganda":               { male: 21.6, female: 23.8 },
  "rwanda":               { male: 21.4, female: 23.5 },
  "ethiopia":             { male: 20.0, female: 21.8 },
  "mauritius":            { male: 25.2, female: 26.8 },
  "australia":            { male: 27.5, female: 26.6 },
  "cyprus":               { male: 27.2, female: 25.8 },
  "malta":                { male: 27.5, female: 26.0 },
  "mongolia":             { male: 25.0, female: 26.2 },
  "cuba":                 { male: 25.0, female: 27.0 },
  "jamaica":              { male: 24.8, female: 29.2 },
  "netherlands":          { male: 26.0, female: 24.8 },
  "belgium":              { male: 26.5, female: 25.2 },
  "austria":              { male: 26.5, female: 24.8 },
  "switzerland":          { male: 26.0, female: 24.2 },
  "norway":               { male: 26.8, female: 25.2 },
  "denmark":              { male: 26.4, female: 24.8 },
  "finland":              { male: 27.0, female: 25.6 },
  "ireland":              { male: 27.5, female: 26.4 },
  "slovakia":             { male: 27.2, female: 25.8 },
  "lithuania":            { male: 27.0, female: 26.0 },
  "latvia":               { male: 26.6, female: 26.2 },
  "slovenia":             { male: 26.8, female: 25.0 },
  "luxembourg":           { male: 26.4, female: 24.5 },
  "iceland":              { male: 27.0, female: 25.5 },
  "bosnia-and-herzegovina": { male: 26.5, female: 26.0 },
  "moldova":              { male: 26.0, female: 27.2 },
};

export function getCountryBmi(slug: string): BmiByGender | undefined {
  return COUNTRY_BMI[slug];
}

/** Slugs that have ethnicity- and BMI-accurate reference images in /bmi/country/ */
export const COUNTRY_BMI_IMAGE_SLUGS = [
  "philippines",
  "thailand",
  "japan",
  "mexico",
  "indonesia",
  "vietnam",
  "colombia",
] as const;

export function hasCountryBmiImage(slug: string): boolean {
  return (COUNTRY_BMI_IMAGE_SLUGS as readonly string[]).includes(slug);
}
