/**
 * Canonical English display names for every curated country.
 * Use these so the UI always shows English names regardless of database locale.
 */
export const COUNTRY_DISPLAY_NAMES: Record<string, string> = {
  "philippines": "Philippines",
  "thailand": "Thailand",
  "indonesia": "Indonesia",
  "malaysia": "Malaysia",
  "vietnam": "Vietnam",
  "cambodia": "Cambodia",
  "kenya": "Kenya",
  "nigeria": "Nigeria",
  "uganda": "Uganda",
  "rwanda": "Rwanda",
  "tanzania": "Tanzania",
  "ethiopia": "Ethiopia",
  "bolivia": "Bolivia",
  "colombia": "Colombia",
  "mexico": "Mexico",
  "peru": "Peru",
  "venezuela": "Venezuela",
  "dominican-republic": "Dominican Republic",
  "costa-rica": "Costa Rica",
  "india": "India",
  "pakistan": "Pakistan",
  "morocco": "Morocco",
  "brazil": "Brazil",
  "argentina": "Argentina",
  "chile": "Chile",
  "china": "China",
  "mongolia": "Mongolia",
  "south-africa": "South Africa",
  "russia": "Russia",
  "ukraine": "Ukraine",
  "poland": "Poland",
  "romania": "Romania",
  "turkey": "Turkey",
  "kazakhstan": "Kazakhstan",
  "algeria": "Algeria",
  "libya": "Libya",
  "usa": "United States",
  "canada": "Canada",
  "australia": "Australia",
  "uk": "United Kingdom",
  "france": "France",
  "germany": "Germany",
  "spain": "Spain",
  "italy": "Italy",
  "sweden": "Sweden",
  "japan": "Japan",
  "south-korea": "South Korea",
  "saudi-arabia": "Saudi Arabia",
  "egypt": "Egypt",
  "iran": "Iran",
  "portugal": "Portugal",
  "netherlands": "Netherlands",
  "belgium": "Belgium",
  "austria": "Austria",
  "switzerland": "Switzerland",
  "norway": "Norway",
  "denmark": "Denmark",
  "finland": "Finland",
  "ireland": "Ireland",
  "greece": "Greece",
  "czech-republic": "Czech Republic",
  "hungary": "Hungary",
  "croatia": "Croatia",
  "serbia": "Serbia",
  "bulgaria": "Bulgaria",
  "slovakia": "Slovakia",
  "lithuania": "Lithuania",
  "latvia": "Latvia",
  "estonia": "Estonia",
  "slovenia": "Slovenia",
  "luxembourg": "Luxembourg",
  "malta": "Malta",
  "cyprus": "Cyprus",
  "iceland": "Iceland",
  "montenegro": "Montenegro",
  "north-macedonia": "North Macedonia",
  "albania": "Albania",
  "bosnia-and-herzegovina": "Bosnia and Herzegovina",
  "moldova": "Moldova",
};

export function getCountryDisplayName(slug: string): string {
  return COUNTRY_DISPLAY_NAMES[slug] ?? slug;
}
