export type CountryFilterMeta = {
  receptiveness: string;
  localValues: string;
  englishProficiency: string;
  budgetTier: string;
  visaEase: string;
  internetSpeed: string;
  internetMbps?: number;
  climate: string;
  vibe: string;
  safetyLevel: string;
  healthcareQuality: string;
};

export const DEFAULT_COUNTRY_FILTER_META: CountryFilterMeta = {
  receptiveness: "Medium",
  localValues: "Mixed",
  englishProficiency: "Moderate",
  budgetTier: "$1k-$2k",
  visaEase: "Visa-Free",
  internetSpeed: "Moderate",
  climate: "Temperate",
  vibe: "",
  safetyLevel: "Moderate",
  healthcareQuality: "Moderate",
};

export const COUNTRY_FILTER_DATA: Record<string, CountryFilterMeta> = {
  "philippines": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "High",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Moderate",
    "climate": "Tropical",
    "vibe": "Beach Access, Nature/Mountains, Great Nightlife",
    "safetyLevel": "Dangerous",
    "healthcareQuality": "Moderate",
    "internetMbps": 103.91
  },
  "thailand": {
    "receptiveness": "High",
    "localValues": "Mixed",
    "englishProficiency": "Moderate",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Tropical",
    "vibe": "Great Nightlife, Beach Access, Nature/Mountains",
    "safetyLevel": "Moderate",
    "healthcareQuality": "High",
    "internetMbps": 272.99
  },
  "indonesia": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "Moderate",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Moderate",
    "climate": "Tropical",
    "vibe": "Beach Access, Nature/Mountains, Great Nightlife",
    "safetyLevel": "Safe",
    "healthcareQuality": "Moderate",
    "internetMbps": 44.62
  },
  "malaysia": {
    "receptiveness": "Medium",
    "localValues": "Traditional",
    "englishProficiency": "High",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Tropical",
    "vibe": "Great Nightlife, Nature/Mountains",
    "safetyLevel": "Safe",
    "healthcareQuality": "High",
    "internetMbps": 165.48
  },
  "vietnam": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "Moderate",
    "budgetTier": "<$1k",
    "visaEase": "e-Visa",
    "internetSpeed": "Fast",
    "climate": "Tropical",
    "vibe": "Great Nightlife, Nature/Mountains, Beach Access",
    "safetyLevel": "Safe",
    "healthcareQuality": "Moderate",
    "internetMbps": 284.99
  },
  "cambodia": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "Low",
    "budgetTier": "<$1k",
    "visaEase": "e-Visa",
    "internetSpeed": "Moderate",
    "climate": "Tropical",
    "vibe": "Great Nightlife, Nature/Mountains",
    "safetyLevel": "Moderate",
    "healthcareQuality": "Low",
    "internetMbps": 50.88
  },
  "kenya": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "High",
    "budgetTier": "$1k-$2k",
    "visaEase": "e-Visa",
    "internetSpeed": "Moderate",
    "climate": "Tropical",
    "vibe": "Nature/Mountains, Great Nightlife",
    "safetyLevel": "Moderate",
    "healthcareQuality": "Moderate",
    "internetMbps": 15.92
  },
  "nigeria": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "High",
    "budgetTier": "$1k-$2k",
    "visaEase": "Difficult",
    "internetSpeed": "Moderate",
    "climate": "Tropical",
    "vibe": "Great Nightlife",
    "safetyLevel": "Dangerous",
    "healthcareQuality": "Low",
    "internetMbps": 35.93
  },
  "uganda": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "High",
    "budgetTier": "<$1k",
    "visaEase": "e-Visa",
    "internetSpeed": "Slow",
    "climate": "Tropical",
    "vibe": "Nature/Mountains",
    "safetyLevel": "Moderate",
    "healthcareQuality": "Low",
    "internetMbps": 28.66
  },
  "rwanda": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "High",
    "budgetTier": "$1k-$2k",
    "visaEase": "e-Visa",
    "internetSpeed": "Moderate",
    "climate": "Tropical",
    "vibe": "Nature/Mountains",
    "safetyLevel": "Safe",
    "healthcareQuality": "Moderate",
    "internetMbps": 41.98
  },
  "tanzania": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "Moderate",
    "budgetTier": "$1k-$2k",
    "visaEase": "e-Visa",
    "internetSpeed": "Moderate",
    "climate": "Tropical",
    "vibe": "Nature/Mountains, Beach Access",
    "safetyLevel": "Moderate",
    "healthcareQuality": "Low",
    "internetMbps": 22.11
  },
  "ethiopia": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "Moderate",
    "budgetTier": "<$1k",
    "visaEase": "e-Visa",
    "internetSpeed": "Slow",
    "climate": "Tropical",
    "vibe": "Nature/Mountains",
    "safetyLevel": "Dangerous",
    "healthcareQuality": "Low"
  },
  "bolivia": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "Low",
    "budgetTier": "<$1k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Slow",
    "climate": "Temperate",
    "vibe": "Nature/Mountains",
    "safetyLevel": "Moderate",
    "healthcareQuality": "Low",
    "internetMbps": 62.99
  },
  "colombia": {
    "receptiveness": "High",
    "localValues": "Mixed",
    "englishProficiency": "Low",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Tropical",
    "vibe": "Great Nightlife, Nature/Mountains, Beach Access",
    "safetyLevel": "Dangerous",
    "healthcareQuality": "Moderate",
    "internetMbps": 208.11
  },
  "mexico": {
    "receptiveness": "High",
    "localValues": "Mixed",
    "englishProficiency": "Moderate",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Tropical",
    "vibe": "Great Nightlife, Beach Access, Nature/Mountains",
    "safetyLevel": "Dangerous",
    "healthcareQuality": "Moderate",
    "internetMbps": 93.19
  },
  "peru": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "Low",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Moderate",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Nature/Mountains, Beach Access",
    "safetyLevel": "Moderate",
    "healthcareQuality": "Moderate",
    "internetMbps": 256.52
  },
  "venezuela": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "Low",
    "budgetTier": "<$1k",
    "visaEase": "Difficult",
    "internetSpeed": "Slow",
    "climate": "Tropical",
    "vibe": "Beach Access, Nature/Mountains",
    "safetyLevel": "Dangerous",
    "healthcareQuality": "Low",
    "internetMbps": 96.6
  },
  "dominican-republic": {
    "receptiveness": "High",
    "localValues": "Mixed",
    "englishProficiency": "Low",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Moderate",
    "climate": "Tropical",
    "vibe": "Great Nightlife, Beach Access",
    "safetyLevel": "Moderate",
    "healthcareQuality": "Moderate",
    "internetMbps": 73.07
  },
  "costa-rica": {
    "receptiveness": "High",
    "localValues": "Mixed",
    "englishProficiency": "High",
    "budgetTier": "$2k-$3k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Tropical",
    "vibe": "Nature/Mountains, Beach Access",
    "safetyLevel": "Safe",
    "healthcareQuality": "High",
    "internetMbps": 161.77
  },
  "india": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "High",
    "budgetTier": "<$1k",
    "visaEase": "e-Visa",
    "internetSpeed": "Moderate",
    "climate": "Tropical",
    "vibe": "Nature/Mountains, Beach Access",
    "safetyLevel": "Moderate",
    "healthcareQuality": "Moderate",
    "internetMbps": 61.67
  },
  "pakistan": {
    "receptiveness": "Low",
    "localValues": "Traditional",
    "englishProficiency": "Moderate",
    "budgetTier": "<$1k",
    "visaEase": "e-Visa",
    "internetSpeed": "Moderate",
    "climate": "Temperate",
    "vibe": "Nature/Mountains",
    "safetyLevel": "Dangerous",
    "healthcareQuality": "Low",
    "internetMbps": 18.06
  },
  "morocco": {
    "receptiveness": "Medium",
    "localValues": "Traditional",
    "englishProficiency": "Moderate",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Moderate",
    "climate": "Temperate",
    "vibe": "Beach Access, Nature/Mountains",
    "safetyLevel": "Safe",
    "healthcareQuality": "Moderate",
    "internetMbps": 55.71
  },
  "brazil": {
    "receptiveness": "High",
    "localValues": "Modern",
    "englishProficiency": "Low",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Tropical",
    "vibe": "Great Nightlife, Beach Access, Nature/Mountains",
    "safetyLevel": "Moderate",
    "healthcareQuality": "Moderate",
    "internetMbps": 222.3
  },
  "argentina": {
    "receptiveness": "High",
    "localValues": "Mixed",
    "englishProficiency": "Moderate",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Nature/Mountains",
    "safetyLevel": "Safe",
    "healthcareQuality": "High",
    "internetMbps": 113.33
  },
  "chile": {
    "receptiveness": "Medium",
    "localValues": "Modern",
    "englishProficiency": "Moderate",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Nature/Mountains, Beach Access",
    "safetyLevel": "Safe",
    "healthcareQuality": "High",
    "internetMbps": 337.86
  },
  "china": {
    "receptiveness": "Medium",
    "localValues": "Traditional",
    "englishProficiency": "Low",
    "budgetTier": "$2k-$3k",
    "visaEase": "Difficult",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Nature/Mountains",
    "safetyLevel": "Safe",
    "healthcareQuality": "Moderate",
    "internetMbps": 216.96
  },
  "mongolia": {
    "receptiveness": "Medium",
    "localValues": "Traditional",
    "englishProficiency": "Low",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Moderate",
    "climate": "Cold",
    "vibe": "Nature/Mountains",
    "safetyLevel": "Safe",
    "healthcareQuality": "Low",
    "internetMbps": 81.13
  },
  "south-africa": {
    "receptiveness": "High",
    "localValues": "Mixed",
    "englishProficiency": "High",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Beach Access, Nature/Mountains",
    "safetyLevel": "Dangerous",
    "healthcareQuality": "High",
    "internetMbps": 48.39
  },
  "russia": {
    "receptiveness": "Medium",
    "localValues": "Traditional",
    "englishProficiency": "Low",
    "budgetTier": "$1k-$2k",
    "visaEase": "Difficult",
    "internetSpeed": "Fast",
    "climate": "Cold",
    "vibe": "Great Nightlife",
    "safetyLevel": "Dangerous",
    "healthcareQuality": "Moderate",
    "internetMbps": 91.34
  },
  "ukraine": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "Moderate",
    "budgetTier": "<$1k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Cold",
    "vibe": "Great Nightlife",
    "safetyLevel": "Dangerous",
    "healthcareQuality": "Moderate",
    "internetMbps": 91.38
  },
  "poland": {
    "receptiveness": "Medium",
    "localValues": "Modern",
    "englishProficiency": "High",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Cold",
    "vibe": "Great Nightlife, Nature/Mountains",
    "safetyLevel": "Safe",
    "healthcareQuality": "High",
    "internetMbps": 214.57
  },
  "romania": {
    "receptiveness": "High",
    "localValues": "Mixed",
    "englishProficiency": "High",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Nature/Mountains",
    "safetyLevel": "Safe",
    "healthcareQuality": "Moderate",
    "internetMbps": 268.82
  },
  "turkey": {
    "receptiveness": "High",
    "localValues": "Traditional",
    "englishProficiency": "Moderate",
    "budgetTier": "$1k-$2k",
    "visaEase": "e-Visa",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Beach Access, Nature/Mountains",
    "safetyLevel": "Dangerous",
    "healthcareQuality": "High",
    "internetMbps": 75.34
  },
  "kazakhstan": {
    "receptiveness": "Medium",
    "localValues": "Mixed",
    "englishProficiency": "Low",
    "budgetTier": "$1k-$2k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Cold",
    "vibe": "Nature/Mountains",
    "safetyLevel": "Safe",
    "healthcareQuality": "Moderate",
    "internetMbps": 87.17
  },
  "algeria": {
    "receptiveness": "Low",
    "localValues": "Traditional",
    "englishProficiency": "Low",
    "budgetTier": "$1k-$2k",
    "visaEase": "Difficult",
    "internetSpeed": "Moderate",
    "climate": "Temperate",
    "vibe": "Beach Access",
    "safetyLevel": "Moderate",
    "healthcareQuality": "Low",
    "internetMbps": 55.13
  },
  "libya": {
    "receptiveness": "Low",
    "localValues": "Traditional",
    "englishProficiency": "Low",
    "budgetTier": "$1k-$2k",
    "visaEase": "Difficult",
    "internetSpeed": "Slow",
    "climate": "Tropical",
    "vibe": "Beach Access",
    "safetyLevel": "Dangerous",
    "healthcareQuality": "Low",
    "internetMbps": 10.96
  },
  "usa": {
    "receptiveness": "Low",
    "localValues": "Modern",
    "englishProficiency": "High",
    "budgetTier": "$3k+",
    "visaEase": "Difficult",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Beach Access, Nature/Mountains",
    "safetyLevel": "Moderate",
    "healthcareQuality": "High",
    "internetMbps": 306.15
  },
  "canada": {
    "receptiveness": "Low",
    "localValues": "Modern",
    "englishProficiency": "High",
    "budgetTier": "$3k+",
    "visaEase": "Difficult",
    "internetSpeed": "Fast",
    "climate": "Cold",
    "vibe": "Great Nightlife, Nature/Mountains",
    "safetyLevel": "Very Safe",
    "healthcareQuality": "High",
    "internetMbps": 274.35
  },
  "australia": {
    "receptiveness": "Low",
    "localValues": "Modern",
    "englishProficiency": "High",
    "budgetTier": "$3k+",
    "visaEase": "Difficult",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Beach Access, Nature/Mountains",
    "safetyLevel": "Very Safe",
    "healthcareQuality": "High",
    "internetMbps": 158.62
  },
  "uk": {
    "receptiveness": "Low",
    "localValues": "Modern",
    "englishProficiency": "High",
    "budgetTier": "$3k+",
    "visaEase": "Difficult",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Nature/Mountains",
    "safetyLevel": "Safe",
    "healthcareQuality": "High",
    "internetMbps": 166.28
  },
  "france": {
    "receptiveness": "Low",
    "localValues": "Modern",
    "englishProficiency": "Moderate",
    "budgetTier": "$3k+",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Beach Access, Nature/Mountains",
    "safetyLevel": "Safe",
    "healthcareQuality": "High",
    "internetMbps": 348.02
  },
  "germany": {
    "receptiveness": "Low",
    "localValues": "Modern",
    "englishProficiency": "High",
    "budgetTier": "$2k-$3k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Nature/Mountains",
    "safetyLevel": "Very Safe",
    "healthcareQuality": "High",
    "internetMbps": 102.67
  },
  "spain": {
    "receptiveness": "Low",
    "localValues": "Modern",
    "englishProficiency": "Moderate",
    "budgetTier": "$2k-$3k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Beach Access, Nature/Mountains",
    "safetyLevel": "Safe",
    "healthcareQuality": "High",
    "internetMbps": 274.21
  },
  "italy": {
    "receptiveness": "Low",
    "localValues": "Mixed",
    "englishProficiency": "Moderate",
    "budgetTier": "$2k-$3k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Beach Access, Nature/Mountains",
    "safetyLevel": "Safe",
    "healthcareQuality": "High",
    "internetMbps": 113.34
  },
  "sweden": {
    "receptiveness": "Low",
    "localValues": "Modern",
    "englishProficiency": "High",
    "budgetTier": "$3k+",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Cold",
    "vibe": "Great Nightlife, Nature/Mountains",
    "safetyLevel": "Very Safe",
    "healthcareQuality": "High",
    "internetMbps": 203.36
  },
  "japan": {
    "receptiveness": "Medium",
    "localValues": "Traditional",
    "englishProficiency": "Low",
    "budgetTier": "$2k-$3k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Nature/Mountains",
    "safetyLevel": "Very Safe",
    "healthcareQuality": "High",
    "internetMbps": 248.85
  },
  "south-korea": {
    "receptiveness": "Low",
    "localValues": "Modern",
    "englishProficiency": "Moderate",
    "budgetTier": "$2k-$3k",
    "visaEase": "Visa-Free",
    "internetSpeed": "Fast",
    "climate": "Temperate",
    "vibe": "Great Nightlife, Nature/Mountains",
    "safetyLevel": "Very Safe",
    "healthcareQuality": "High",
    "internetMbps": 247.37
  },
  "saudi-arabia": {
    "receptiveness": "Low",
    "localValues": "Traditional",
    "englishProficiency": "Moderate",
    "budgetTier": "$3k+",
    "visaEase": "e-Visa",
    "internetSpeed": "Fast",
    "climate": "Tropical",
    "vibe": "Great Nightlife",
    "safetyLevel": "Safe",
    "healthcareQuality": "High",
    "internetMbps": 160.79
  },
  "egypt": {
    "receptiveness": "Low",
    "localValues": "Traditional",
    "englishProficiency": "Moderate",
    "budgetTier": "<$1k",
    "visaEase": "e-Visa",
    "internetSpeed": "Moderate",
    "climate": "Tropical",
    "vibe": "Beach Access",
    "safetyLevel": "Moderate",
    "healthcareQuality": "Moderate",
    "internetMbps": 91.62
  },
  "iran": {
    "receptiveness": "Low",
    "localValues": "Traditional",
    "englishProficiency": "Low",
    "budgetTier": "<$1k",
    "visaEase": "Difficult",
    "internetSpeed": "Moderate",
    "climate": "Temperate",
    "vibe": "Nature/Mountains",
    "safetyLevel": "Dangerous",
    "healthcareQuality": "Moderate",
    "internetMbps": 22.05
  }
};
