/**
 * Standardized "8 women group" image per country.
 * Same format for all: 8 women in a row, clean white background, hyper realistic.
 * Image path: /women-group/{slug}.png (files in public/women-group/).
 */
export const WOMEN_GROUP_IMAGE: Record<string, string> = {
  philippines: "/women-group/philippines.png",
  thailand: "/women-group/thailand.png",
  indonesia: "/women-group/indonesia.png",
  malaysia: "/women-group/malaysia.png",
  vietnam: "/women-group/vietnam.png",
  cambodia: "/women-group/cambodia.png",
  kenya: "/women-group/kenya.png",
  nigeria: "/women-group/nigeria.png",
  uganda: "/women-group/uganda.png",
  rwanda: "/women-group/rwanda.png",
  tanzania: "/women-group/tanzania.png",
  ethiopia: "/women-group/ethiopia.png",
  bolivia: "/women-group/bolivia.png",
  colombia: "/women-group/colombia.png",
  mexico: "/women-group/mexico.png",
  peru: "/women-group/peru.png",
  venezuela: "/women-group/venezuela.png",
  "dominican-republic": "/women-group/dominican-republic.png",
  "costa-rica": "/women-group/costa-rica.png",
  india: "/women-group/india.png",
  pakistan: "/women-group/pakistan.png",
  morocco: "/women-group/morocco.png",
  brazil: "/women-group/brazil.png",
  argentina: "/women-group/argentina.png",
  chile: "/women-group/chile.png",
  china: "/women-group/china.png",
  mongolia: "/women-group/mongolia.png",
  "south-africa": "/women-group/south-africa.png",
  russia: "/women-group/russia.png",
  ukraine: "/women-group/ukraine.png",
  poland: "/women-group/poland.png",
  romania: "/women-group/romania.png",
  turkey: "/women-group/turkey.png",
  kazakhstan: "/women-group/kazakhstan.png",
  algeria: "/women-group/algeria.png",
  libya: "/women-group/libya.png",
  usa: "/women-group/usa.png",
  canada: "/women-group/canada.png",
  australia: "/women-group/australia.png",
  uk: "/women-group/uk.png",
  france: "/women-group/france.png",
  germany: "/women-group/germany.png",
  spain: "/women-group/spain.png",
  italy: "/women-group/italy.png",
  sweden: "/women-group/sweden.png",
  japan: "/women-group/japan.png",
  "south-korea": "/women-group/south-korea.png",
  "saudi-arabia": "/women-group/saudi-arabia.png",
  egypt: "/women-group/egypt.png",
  iran: "/women-group/iran.png",
  "portugal": "/women-group/portugal.png",
  "netherlands": "/women-group/netherlands.png",
  "belgium": "/women-group/belgium.png",
  "austria": "/women-group/austria.png",
  "switzerland": "/women-group/switzerland.png",
  "norway": "/women-group/norway.png",
  "denmark": "/women-group/denmark.png",
  "finland": "/women-group/finland.png",
  "ireland": "/women-group/ireland.png",
  "greece": "/women-group/greece.png",
  "czech-republic": "/women-group/czech-republic.png",
  "hungary": "/women-group/hungary.png",
  "croatia": "/women-group/croatia.png",
  "serbia": "/women-group/serbia.png",
  "bulgaria": "/women-group/bulgaria.png",
  "slovakia": "/women-group/slovakia.png",
  "lithuania": "/women-group/lithuania.png",
  "latvia": "/women-group/latvia.png",
  "estonia": "/women-group/estonia.png",
  "slovenia": "/women-group/slovenia.png",
  "luxembourg": "/women-group/luxembourg.png",
  "malta": "/women-group/malta.png",
  "cyprus": "/women-group/cyprus.png",
  "iceland": "/women-group/iceland.png",
  "montenegro": "/women-group/montenegro.png",
  "north-macedonia": "/women-group/north-macedonia.png",
  "albania": "/women-group/albania.png",
  "bosnia-and-herzegovina": "/women-group/bosnia-and-herzegovina.png",
  "moldova": "/women-group/moldova.png",
  "taiwan": "/women-group/taiwan.png",
  "singapore": "/women-group/singapore.png",
  "laos": "/women-group/laos.png",
  "sri-lanka": "/women-group/sri-lanka.png",
  "ecuador": "/women-group/ecuador.png",
  "paraguay": "/women-group/paraguay.png",
  "uruguay": "/women-group/uruguay.png",
  "panama": "/women-group/panama.png",
  "guatemala": "/women-group/guatemala.png",
  "cuba": "/women-group/cuba.png",
  "jamaica": "/women-group/jamaica.png",
  "georgia": "/women-group/georgia.png",
  "united-arab-emirates": "/women-group/united-arab-emirates.png",
  "mauritius": "/women-group/mauritius.png",
  "belarus": "/women-group/belarus.png",
  "brunei": "/women-group/brunei.png",
  "myanmar": "/women-group/myanmar.png",
  "timor-leste": "/women-group/timor-leste.png",
  "angola": "/women-group/angola.png",
  "belize": "/women-group/belize.png",
  "benin": "/women-group/benin.png",
  "botswana": "/women-group/botswana.png",
  "british-indian-ocean-territory": "/women-group/british-indian-ocean-territory.png",
  "burkina-faso": "/women-group/burkina-faso.png",
  "burundi": "/women-group/burundi.png",
  "cameroon": "/women-group/cameroon.png",
  "cape-verde": "/women-group/cape-verde.png",
  "central-african-republic": "/women-group/central-african-republic.png",
  "chad": "/women-group/chad.png",
  "comoros": "/women-group/comoros.png",
  "djibouti": "/women-group/djibouti.png",
  "dr-congo": "/women-group/dr-congo.png",
  "el-salvador": "/women-group/el-salvador.png",
  "equatorial-guinea": "/women-group/equatorial-guinea.png",
  "eritrea": "/women-group/eritrea.png",
  "eswatini": "/women-group/eswatini.png",
  "falkland-islands": "/women-group/falkland-islands.png",
  "french-guiana": "/women-group/french-guiana.png",
  "gabon": "/women-group/gabon.png",
  "gambia": "/women-group/gambia.png",
  "ghana": "/women-group/ghana.png",
  "guinea": "/women-group/guinea.png",
  "guinea-bissau": "/women-group/guinea-bissau.png",
  "guyana": "/women-group/guyana.png",
  "honduras": "/women-group/honduras.png",
  "ivory-coast": "/women-group/ivory-coast.png",
  "lesotho": "/women-group/lesotho.png",
  "liberia": "/women-group/liberia.png",
  "madagascar": "/women-group/madagascar.png",
  "malawi": "/women-group/malawi.png",
  "mali": "/women-group/mali.png",
  "mauritania": "/women-group/mauritania.png",
  "mayotte": "/women-group/mayotte.png",
  "mozambique": "/women-group/mozambique.png",
  "namibia": "/women-group/namibia.png",
  "nicaragua": "/women-group/nicaragua.png",
  "niger": "/women-group/niger.png",
  "republic-of-the-congo": "/women-group/republic-of-the-congo.png",
  "reunion": "/women-group/reunion.png",
  "saint-helena-ascension-and-tristan-da-cunha": "/women-group/saint-helena-ascension-and-tristan-da-cunha.png",
  "sao-tome-and-principe": "/women-group/sao-tome-and-principe.png",
  "senegal": "/women-group/senegal.png",
  "seychelles": "/women-group/seychelles.png",
  "sierra-leone": "/women-group/sierra-leone.png",
  "somalia": "/women-group/somalia.png",
  "south-sudan": "/women-group/south-sudan.png",
  "suriname": "/women-group/suriname.png",
  "togo": "/women-group/togo.png",
  "zambia": "/women-group/zambia.png",
  "zimbabwe": "/women-group/zimbabwe.png",
  "american-samoa": "/women-group/american-samoa.png",
  "christmas-island": "/women-group/christmas-island.png",
  "cocos-keeling-islands": "/women-group/cocos-keeling-islands.png",
  "cook-islands": "/women-group/cook-islands.png",
  "fiji": "/women-group/fiji.png",
  "french-polynesia": "/women-group/french-polynesia.png",
  "guam": "/women-group/guam.png",
  "kiribati": "/women-group/kiribati.png",
  "marshall-islands": "/women-group/marshall-islands.png",
  "micronesia": "/women-group/micronesia.png",
  "nauru": "/women-group/nauru.png",
  "new-caledonia": "/women-group/new-caledonia.png",
  "niue": "/women-group/niue.png",
  "norfolk-island": "/women-group/norfolk-island.png",
  "northern-mariana-islands": "/women-group/northern-mariana-islands.png",
  "palau": "/women-group/palau.png",
  "papua-new-guinea": "/women-group/papua-new-guinea.png",
  "pitcairn-islands": "/women-group/pitcairn-islands.png",
  "samoa": "/women-group/samoa.png",
  "solomon-islands": "/women-group/solomon-islands.png",
  "tokelau": "/women-group/tokelau.png",
  "tonga": "/women-group/tonga.png",
  "tuvalu": "/women-group/tuvalu.png",
  "vanuatu": "/women-group/vanuatu.png",
  "wallis-and-futuna": "/women-group/wallis-and-futuna.png",
  "afghanistan": "/women-group/afghanistan.png",
  "anguilla": "/women-group/anguilla.png",
  "antarctica": "/women-group/antarctica.png",
  "antigua-and-barbuda": "/women-group/antigua-and-barbuda.png",
  "aruba": "/women-group/aruba.png",
  "bahamas": "/women-group/bahamas.png",
  "bangladesh": "/women-group/bangladesh.png",
  "barbados": "/women-group/barbados.png",
  "bhutan": "/women-group/bhutan.png",
  "bouvet-island": "/women-group/bouvet-island.png",
  "british-virgin-islands": "/women-group/british-virgin-islands.png",
  "caribbean-netherlands": "/women-group/caribbean-netherlands.png",
  "cayman-islands": "/women-group/cayman-islands.png",
  "curacao": "/women-group/curacao.png",
  "dominica": "/women-group/dominica.png",
  "french-southern-and-antarctic-lands": "/women-group/french-southern-and-antarctic-lands.png",
  "grenada": "/women-group/grenada.png",
  "guadeloupe": "/women-group/guadeloupe.png",
  "haiti": "/women-group/haiti.png",
  "heard-island-and-mcdonald-islands": "/women-group/heard-island-and-mcdonald-islands.png",
  "kyrgyzstan": "/women-group/kyrgyzstan.png",
  "maldives": "/women-group/maldives.png",
  "martinique": "/women-group/martinique.png",
  "montserrat": "/women-group/montserrat.png",
  "nepal": "/women-group/nepal.png",
  "puerto-rico": "/women-group/puerto-rico.png",
  "saint-barthelemy": "/women-group/saint-barthelemy.png",
  "saint-kitts-and-nevis": "/women-group/saint-kitts-and-nevis.png",
  "saint-lucia": "/women-group/saint-lucia.png",
  "saint-martin": "/women-group/saint-martin.png",
  "saint-vincent-and-the-grenadines": "/women-group/saint-vincent-and-the-grenadines.png",
  "sint-maarten": "/women-group/sint-maarten.png",
  "south-georgia": "/women-group/south-georgia.png",
  "sudan": "/women-group/sudan.png",
  "tajikistan": "/women-group/tajikistan.png",
  "trinidad-and-tobago": "/women-group/trinidad-and-tobago.png",
  "tunisia": "/women-group/tunisia.png",
  "turkmenistan": "/women-group/turkmenistan.png",
  "turks-and-caicos-islands": "/women-group/turks-and-caicos-islands.png",
  "united-states-virgin-islands": "/women-group/united-states-virgin-islands.png",
  "uzbekistan": "/women-group/uzbekistan.png",
  "western-sahara": "/women-group/western-sahara.png",
  "armenia": "/women-group/armenia.png",
  "azerbaijan": "/women-group/azerbaijan.png",
  "bahrain": "/women-group/bahrain.png",
  "hong-kong": "/women-group/hong-kong.png",
  "iraq": "/women-group/iraq.png",
  "israel": "/women-group/israel.png",
  "jordan": "/women-group/jordan.png",
  "kuwait": "/women-group/kuwait.png",
  "lebanon": "/women-group/lebanon.png",
  "macau": "/women-group/macau.png",
  "north-korea": "/women-group/north-korea.png",
  "oman": "/women-group/oman.png",
  "palestine": "/women-group/palestine.png",
  "qatar": "/women-group/qatar.png",
  "syria": "/women-group/syria.png",
  "yemen": "/women-group/yemen.png",
  "andorra": "/women-group/andorra.png",
  "gibraltar": "/women-group/gibraltar.png",
  "kosovo": "/women-group/kosovo.png",
  "san-marino": "/women-group/san-marino.png",
  "vatican-city": "/women-group/vatican-city.png",
  "aland-islands": "/women-group/aland-islands.png",
  "faroe-islands": "/women-group/faroe-islands.png",
  "guernsey": "/women-group/guernsey.png",
  "isle-of-man": "/women-group/isle-of-man.png",
  "jersey": "/women-group/jersey.png",
  "liechtenstein": "/women-group/liechtenstein.png",
  "monaco": "/women-group/monaco.png",
  "svalbard-and-jan-mayen": "/women-group/svalbard-and-jan-mayen.png",
  "bermuda": "/women-group/bermuda.png",
  "greenland": "/women-group/greenland.png",
  "new-zealand": "/women-group/new-zealand.png",
  "saint-pierre-and-miquelon": "/women-group/saint-pierre-and-miquelon.png",
  "united-states-minor-outlying-islands": "/women-group/united-states-minor-outlying-islands.png",
};

/** One-line diversity description for image generation. Same format prompt, only this varies by country. */
export const WOMEN_GROUP_PROMPT_DESCRIPTION: Record<string, string> = {
  philippines: "Filipino women, typical Southeast Asian features, varied skin tones and black to brown hair",
  thailand: "Thai women, typical Thai features, varied skin tones and hair",
  indonesia: "Indonesian women, diverse archipelago look, varied skin and hair",
  malaysia: "Malaysian women, mix of Malay, Chinese and Indian looks, varied",
  vietnam: "Vietnamese women, East Asian features, varied skin and hair",
  cambodia: "Cambodian women, Southeast Asian features, varied",
  kenya: "Kenyan women, East African features, varied skin tones and hair",
  nigeria: "Nigerian women, West African features, varied",
  uganda: "Ugandan women, East African features, varied",
  rwanda: "Rwandan women, East African features, varied",
  tanzania: "Tanzanian women, East African features, varied",
  ethiopia: "Ethiopian women, East African features, varied",
  bolivia: "Bolivian women, Andean and mestizo mix, varied",
  colombia: "Colombian women, Latin American mixed, varied",
  mexico: "Mexican women, Latin American mixed, varied",
  peru: "Peruvian women, Andean and mestizo, varied",
  venezuela: "Venezuelan women, Latin American mixed, varied",
  "dominican-republic": "Dominican women, Caribbean mixed, varied",
  "costa-rica": "Costa Rican women, Latin American mixed, varied",
  india: "Indian women, South Asian features, varied skin tones and hair",
  pakistan: "Pakistani women, South Asian features, varied",
  morocco: "Moroccan women, North African Maghrebi, varied",
  brazil: "Brazilian women, highly diverse mixed ethnicities, varied skin and hair",
  argentina: "Argentine women, Southern European and mestizo mix, varied",
  chile: "Chilean women, Latin American mixed, varied",
  china: "Chinese women, East Asian features, varied",
  mongolia: "Mongolian women, East Asian Central Asian features, varied",
  "south-africa": "South African women, mix of Black, White and Coloured, diverse features",
  russia: "Russian women, Slavic European features, varied hair blonde brown black",
  ukraine: "Ukrainian women, Slavic European features, varied hair",
  poland: "Polish women, Central European features, varied hair",
  romania: "Romanian women, Southeast European features, varied",
  turkey: "Turkish women, Mediterranean and Anatolian, varied",
  kazakhstan: "Kazakh women, Central Asian mixed, varied",
  algeria: "Algerian women, North African Maghrebi, varied",
  libya: "Libyan women, North African, varied",
  usa: "American women, ethnically diverse, varied",
  canada: "Canadian women, ethnically diverse, varied",
  australia: "Australian women, ethnically diverse, varied",
  uk: "British women, ethnically diverse including White British South Asian Black, varied",
  france: "French women, ethnically diverse, European and North African mix, varied",
  germany: "German women, North European features, varied hair blonde brown auburn black",
  spain: "Spanish women, Mediterranean European, varied",
  italy: "Italian women, Mediterranean European, varied",
  sweden: "Swedish women, Nordic features, varied hair blonde light brown",
  japan: "Japanese women, East Asian features, varied",
  "south-korea": "South Korean women, East Asian features, varied",
  "saudi-arabia": "Saudi women, Arabian Peninsula, varied",
  egypt: "Egyptian women, North African Arab, varied",
  iran: "Iranian women, Persian features, varied",
  "portugal": "Portuguese women, Southern European Mediterranean, varied",
  "netherlands": "Dutch women, North European features, varied hair blonde brown",
  "belgium": "Belgian women, Western European mixed Flemish Walloon, varied",
  "austria": "Austrian women, Central European Alpine, varied",
  "switzerland": "Swiss women, Central European diverse, varied",
  "norway": "Norwegian women, Nordic features, varied hair blonde light brown",
  "denmark": "Danish women, Nordic features, varied hair blonde brown",
  "finland": "Finnish women, Nordic Baltic features, varied hair blonde light brown",
  "ireland": "Irish women, Celtic North European, varied hair red blonde brown",
  "greece": "Greek women, Mediterranean Southern European, varied",
  "czech-republic": "Czech women, Central European Slavic, varied",
  "hungary": "Hungarian women, Central European, varied",
  "croatia": "Croatian women, Southeast European Mediterranean, varied",
  "serbia": "Serbian women, Southeast European Slavic, varied",
  "bulgaria": "Bulgarian women, Southeast European Slavic, varied",
  "slovakia": "Slovak women, Central European Slavic, varied",
  "lithuania": "Lithuanian women, Baltic North European, varied",
  "latvia": "Latvian women, Baltic North European, varied",
  "estonia": "Estonian women, Baltic North European, varied",
  "slovenia": "Slovenian women, Central Southeast European, varied",
  "luxembourg": "Luxembourgish women, Western European diverse, varied",
  "malta": "Maltese women, Mediterranean Southern European, varied",
  "cyprus": "Cypriot women, Mediterranean Greek Turkish mix, varied",
  "iceland": "Icelandic women, Nordic features, varied hair blonde light",
  "montenegro": "Montenegrin women, Southeast European Mediterranean, varied",
  "north-macedonia": "North Macedonian women, Southeast European Slavic, varied",
  "albania": "Albanian women, Southeast European Mediterranean, varied",
  "bosnia-and-herzegovina": "Bosnian women, Southeast European Slavic mixed, varied",
  "moldova": "Moldovan women, East European Slavic Romanian mix, varied",
  "taiwan": "Taiwanese women, East Asian features, varied",
  "singapore": "Singaporean women, mixed Chinese Malay Indian features, varied",
  "laos": "Laotian women, Southeast Asian features, varied",
  "sri-lanka": "Sri Lankan women, South Asian features, varied skin tones",
  "ecuador": "Ecuadorian women, Andean and mestizo mix, varied",
  "paraguay": "Paraguayan women, Latin American mestizo mix, varied",
  "uruguay": "Uruguayan women, Southern European and mestizo mix, varied",
  "panama": "Panamanian women, Central American mixed, varied",
  "guatemala": "Guatemalan women, Central American Maya and mestizo, varied",
  "cuba": "Cuban women, Caribbean mixed afro-latina, varied",
  "jamaica": "Jamaican women, Afro-Caribbean features, varied",
  "georgia": "Georgian women, Caucasian transcontinental features, varied",
  "united-arab-emirates": "Emirati women, Arabian Peninsula, varied",
  "mauritius": "Mauritian women, mixed South Asian and Creole features, varied",
  "belarus": "Belarusian women, East European Slavic features, varied",
  "brunei": "Brunei women, Southeast Asia features, varied",
  "myanmar": "Myanmar women, Southeast Asia features, varied",
  "timor-leste": "Timor-Leste women, Southeast Asia features, varied",
  "angola": "Angola women, Africa features, varied",
  "belize": "Belize women, Central America features, varied",
  "benin": "Benin women, Africa features, varied",
  "botswana": "Botswana women, Africa features, varied",
  "british-indian-ocean-territory": "British Indian Ocean Territory women, Africa features, varied",
  "burkina-faso": "Burkina Faso women, Africa features, varied",
  "burundi": "Burundi women, Africa features, varied",
  "cameroon": "Cameroon women, Africa features, varied",
  "cape-verde": "Cape Verde women, Africa features, varied",
  "central-african-republic": "Central African Republic women, Africa features, varied",
  "chad": "Chad women, Africa features, varied",
  "comoros": "Comoros women, Africa features, varied",
  "djibouti": "Djibouti women, Africa features, varied",
  "dr-congo": "DR Congo women, Africa features, varied",
  "el-salvador": "El Salvador women, Central America features, varied",
  "equatorial-guinea": "Equatorial Guinea women, Africa features, varied",
  "eritrea": "Eritrea women, Africa features, varied",
  "eswatini": "Eswatini women, Africa features, varied",
  "falkland-islands": "Falkland Islands women, South America features, varied",
  "french-guiana": "French Guiana women, South America features, varied",
  "gabon": "Gabon women, Africa features, varied",
  "gambia": "Gambia women, Africa features, varied",
  "ghana": "Ghana women, Africa features, varied",
  "guinea": "Guinea women, Africa features, varied",
  "guinea-bissau": "Guinea-Bissau women, Africa features, varied",
  "guyana": "Guyana women, South America features, varied",
  "honduras": "Honduras women, Central America features, varied",
  "ivory-coast": "Ivory Coast women, Africa features, varied",
  "lesotho": "Lesotho women, Africa features, varied",
  "liberia": "Liberia women, Africa features, varied",
  "madagascar": "Madagascar women, Africa features, varied",
  "malawi": "Malawi women, Africa features, varied",
  "mali": "Mali women, Africa features, varied",
  "mauritania": "Mauritania women, Africa features, varied",
  "mayotte": "Mayotte women, Africa features, varied",
  "mozambique": "Mozambique women, Africa features, varied",
  "namibia": "Namibia women, Africa features, varied",
  "nicaragua": "Nicaragua women, Central America features, varied",
  "niger": "Niger women, Africa features, varied",
  "republic-of-the-congo": "Republic of the Congo women, Africa features, varied",
  "reunion": "Réunion women, Africa features, varied",
  "saint-helena-ascension-and-tristan-da-cunha": "Saint Helena, Ascension and Tristan da Cunha women, Africa features, varied",
  "sao-tome-and-principe": "São Tomé and Príncipe women, Africa features, varied",
  "senegal": "Senegal women, Africa features, varied",
  "seychelles": "Seychelles women, Africa features, varied",
  "sierra-leone": "Sierra Leone women, Africa features, varied",
  "somalia": "Somalia women, Africa features, varied",
  "south-sudan": "South Sudan women, Africa features, varied",
  "suriname": "Suriname women, South America features, varied",
  "togo": "Togo women, Africa features, varied",
  "zambia": "Zambia women, Africa features, varied",
  "zimbabwe": "Zimbabwe women, Africa features, varied",
  "american-samoa": "American Samoa women, Oceania features, varied",
  "christmas-island": "Christmas Island women, Oceania features, varied",
  "cocos-keeling-islands": "Cocos (Keeling) Islands women, Oceania features, varied",
  "cook-islands": "Cook Islands women, Oceania features, varied",
  "fiji": "Fiji women, Oceania features, varied",
  "french-polynesia": "French Polynesia women, Oceania features, varied",
  "guam": "Guam women, Oceania features, varied",
  "kiribati": "Kiribati women, Oceania features, varied",
  "marshall-islands": "Marshall Islands women, Oceania features, varied",
  "micronesia": "Micronesia women, Oceania features, varied",
  "nauru": "Nauru women, Oceania features, varied",
  "new-caledonia": "New Caledonia women, Oceania features, varied",
  "niue": "Niue women, Oceania features, varied",
  "norfolk-island": "Norfolk Island women, Oceania features, varied",
  "northern-mariana-islands": "Northern Mariana Islands women, Oceania features, varied",
  "palau": "Palau women, Oceania features, varied",
  "papua-new-guinea": "Papua New Guinea women, Oceania features, varied",
  "pitcairn-islands": "Pitcairn Islands women, Oceania features, varied",
  "samoa": "Samoa women, Oceania features, varied",
  "solomon-islands": "Solomon Islands women, Oceania features, varied",
  "tokelau": "Tokelau women, Oceania features, varied",
  "tonga": "Tonga women, Oceania features, varied",
  "tuvalu": "Tuvalu women, Oceania features, varied",
  "vanuatu": "Vanuatu women, Oceania features, varied",
  "wallis-and-futuna": "Wallis and Futuna women, Oceania features, varied",
  "afghanistan": "Afghanistan women, South Asia features, varied",
  "anguilla": "Anguilla women, Caribbean features, varied",
  "antarctica": "Antarctica women, Antarctic features, varied",
  "antigua-and-barbuda": "Antigua and Barbuda women, Caribbean features, varied",
  "aruba": "Aruba women, Caribbean features, varied",
  "bahamas": "Bahamas women, Caribbean features, varied",
  "bangladesh": "Bangladesh women, South Asia features, varied",
  "barbados": "Barbados women, Caribbean features, varied",
  "bhutan": "Bhutan women, South Asia features, varied",
  "bouvet-island": "Bouvet Island women, Antarctic features, varied",
  "british-virgin-islands": "British Virgin Islands women, Caribbean features, varied",
  "caribbean-netherlands": "Caribbean Netherlands women, Caribbean features, varied",
  "cayman-islands": "Cayman Islands women, Caribbean features, varied",
  "curacao": "Curaçao women, Caribbean features, varied",
  "dominica": "Dominica women, Caribbean features, varied",
  "french-southern-and-antarctic-lands": "French Southern and Antarctic Lands women, Antarctic features, varied",
  "grenada": "Grenada women, Caribbean features, varied",
  "guadeloupe": "Guadeloupe women, Caribbean features, varied",
  "haiti": "Haiti women, Caribbean features, varied",
  "heard-island-and-mcdonald-islands": "Heard Island and McDonald Islands women, Antarctic features, varied",
  "kyrgyzstan": "Kyrgyzstan women, Central Asia features, varied",
  "maldives": "Maldives women, South Asia features, varied",
  "martinique": "Martinique women, Caribbean features, varied",
  "montserrat": "Montserrat women, Caribbean features, varied",
  "nepal": "Nepal women, South Asia features, varied",
  "puerto-rico": "Puerto Rico women, Caribbean features, varied",
  "saint-barthelemy": "Saint Barthélemy women, Caribbean features, varied",
  "saint-kitts-and-nevis": "Saint Kitts and Nevis women, Caribbean features, varied",
  "saint-lucia": "Saint Lucia women, Caribbean features, varied",
  "saint-martin": "Saint Martin women, Caribbean features, varied",
  "saint-vincent-and-the-grenadines": "Saint Vincent and the Grenadines women, Caribbean features, varied",
  "sint-maarten": "Sint Maarten women, Caribbean features, varied",
  "south-georgia": "South Georgia women, Antarctic features, varied",
  "sudan": "Sudan women, Africa features, varied",
  "tajikistan": "Tajikistan women, Central Asia features, varied",
  "trinidad-and-tobago": "Trinidad and Tobago women, Caribbean features, varied",
  "tunisia": "Tunisia women, Africa features, varied",
  "turkmenistan": "Turkmenistan women, Central Asia features, varied",
  "turks-and-caicos-islands": "Turks and Caicos Islands women, Caribbean features, varied",
  "united-states-virgin-islands": "United States Virgin Islands women, Caribbean features, varied",
  "uzbekistan": "Uzbekistan women, Central Asia features, varied",
  "western-sahara": "Western Sahara women, Africa features, varied",
  "armenia": "Armenia women, Middle East features, varied",
  "azerbaijan": "Azerbaijan women, Middle East features, varied",
  "bahrain": "Bahrain women, Middle East features, varied",
  "hong-kong": "Hong Kong women, East Asia features, varied",
  "iraq": "Iraq women, Middle East features, varied",
  "israel": "Israel women, Middle East features, varied",
  "jordan": "Jordan women, Middle East features, varied",
  "kuwait": "Kuwait women, Middle East features, varied",
  "lebanon": "Lebanon women, Middle East features, varied",
  "macau": "Macau women, East Asia features, varied",
  "north-korea": "North Korea women, East Asia features, varied",
  "oman": "Oman women, Middle East features, varied",
  "palestine": "Palestine women, Middle East features, varied",
  "qatar": "Qatar women, Middle East features, varied",
  "syria": "Syria women, Middle East features, varied",
  "yemen": "Yemen women, Middle East features, varied",
  "andorra": "Andorra women, Europe features, varied",
  "gibraltar": "Gibraltar women, Europe features, varied",
  "kosovo": "Kosovo women, Europe features, varied",
  "san-marino": "San Marino women, Europe features, varied",
  "vatican-city": "Vatican City women, Europe features, varied",
  "aland-islands": "Åland Islands women, Europe features, varied",
  "faroe-islands": "Faroe Islands women, Europe features, varied",
  "guernsey": "Guernsey women, Europe features, varied",
  "isle-of-man": "Isle of Man women, Europe features, varied",
  "jersey": "Jersey women, Europe features, varied",
  "liechtenstein": "Liechtenstein women, Europe features, varied",
  "monaco": "Monaco women, Europe features, varied",
  "svalbard-and-jan-mayen": "Svalbard and Jan Mayen women, Europe features, varied",
  "bermuda": "Bermuda women, North America features, varied",
  "greenland": "Greenland women, North America features, varied",
  "new-zealand": "New Zealand women, Oceania features, varied",
  "saint-pierre-and-miquelon": "Saint Pierre and Miquelon women, North America features, varied",
  "united-states-minor-outlying-islands": "United States Minor Outlying Islands women, North America features, varied",
};

export const WOMEN_GROUP_STANDARD_PROMPT_PREFIX =
  "Hyper realistic photograph, 8 women standing in a row side by side, full body visible from head to knees, equal spacing between each person, clean pure white background, even studio lighting, no shadows on background, all women facing camera, neutral friendly expression, women appear 24-26 years old, beautiful as you would see on the street, ";

/** Single portrait for main page card: close-up head-and-shoulders only (same format as Romania card). */
export const SINGLE_PORTRAIT_STANDARD_PROMPT_PREFIX =
  "Hyper realistic photograph, close-up portrait of one woman, head and shoulders only, face and shoulders filling the frame, plain light grey or white background, even studio lighting, no shadows on background, facing camera, neutral friendly expression, woman appears 24-26 years old, beautiful as you would see on the street, ";

/** Full prompt for single portrait. Output path: public/women/{slug}.png */
export function getSinglePortraitPrompt(slug: string): string {
  const desc = WOMEN_GROUP_PROMPT_DESCRIPTION[slug];
  if (!desc) return "";
  return SINGLE_PORTRAIT_STANDARD_PROMPT_PREFIX + desc;
}

/** Full prompt for 8-women group. Output path: public/women-group/{slug}.png */
export function getGroupPortraitPrompt(slug: string): string {
  const desc = WOMEN_GROUP_PROMPT_DESCRIPTION[slug];
  if (!desc) return "";
  return WOMEN_GROUP_STANDARD_PROMPT_PREFIX + desc;
}
