/**
 * Standardized "8 women group" image per country.
 * Same format for all: 8 women in a row, clean white background, hyper realistic.
 * Image path: /women-group/{slug}.png (files in public/women-group/).
 */
export const WOMEN_GROUP_IMAGE: Record<string, string> = {
  philippines: "/women-group/philippines.png",
  thailand: "/women-group/thailand.png",
  indonesia: "/women-group/indonesia.png",
  malaysia: "/women-group/malaysia.png",
  vietnam: "/women-group/vietnam.png",
  cambodia: "/women-group/cambodia.png",
  kenya: "/women-group/kenya.png",
  nigeria: "/women-group/nigeria.png",
  uganda: "/women-group/uganda.png",
  rwanda: "/women-group/rwanda.png",
  tanzania: "/women-group/tanzania.png",
  ethiopia: "/women-group/ethiopia.png",
  bolivia: "/women-group/bolivia.png",
  colombia: "/women-group/colombia.png",
  mexico: "/women-group/mexico.png",
  peru: "/women-group/peru.png",
  venezuela: "/women-group/venezuela.png",
  "dominican-republic": "/women-group/dominican-republic.png",
  "costa-rica": "/women-group/costa-rica.png",
  india: "/women-group/india.png",
  pakistan: "/women-group/pakistan.png",
  morocco: "/women-group/morocco.png",
  brazil: "/women-group/brazil.png",
  argentina: "/women-group/argentina.png",
  chile: "/women-group/chile.png",
  china: "/women-group/china.png",
  mongolia: "/women-group/mongolia.png",
  "south-africa": "/women-group/south-africa.png",
  russia: "/women-group/russia.png",
  ukraine: "/women-group/ukraine.png",
  poland: "/women-group/poland.png",
  romania: "/women-group/romania.png",
  turkey: "/women-group/turkey.png",
  kazakhstan: "/women-group/kazakhstan.png",
  algeria: "/women-group/algeria.png",
  libya: "/women-group/libya.png",
  usa: "/women-group/usa.png",
  canada: "/women-group/canada.png",
  australia: "/women-group/australia.png",
  uk: "/women-group/uk.png",
  france: "/women-group/france.png",
  germany: "/women-group/germany.png",
  spain: "/women-group/spain.png",
  italy: "/women-group/italy.png",
  sweden: "/women-group/sweden.png",
  japan: "/women-group/japan.png",
  "south-korea": "/women-group/south-korea.png",
  "saudi-arabia": "/women-group/saudi-arabia.png",
  egypt: "/women-group/egypt.png",
  iran: "/women-group/iran.png",
};

/** One-line diversity description for image generation. Same format prompt, only this varies by country. */
export const WOMEN_GROUP_PROMPT_DESCRIPTION: Record<string, string> = {
  philippines: "Filipino women, typical Southeast Asian features, varied skin tones and black to brown hair",
  thailand: "Thai women, typical Thai features, varied skin tones and hair",
  indonesia: "Indonesian women, diverse archipelago look, varied skin and hair",
  malaysia: "Malaysian women, mix of Malay, Chinese and Indian looks, varied",
  vietnam: "Vietnamese women, East Asian features, varied skin and hair",
  cambodia: "Cambodian women, Southeast Asian features, varied",
  kenya: "Kenyan women, East African features, varied skin tones and hair",
  nigeria: "Nigerian women, West African features, varied",
  uganda: "Ugandan women, East African features, varied",
  rwanda: "Rwandan women, East African features, varied",
  tanzania: "Tanzanian women, East African features, varied",
  ethiopia: "Ethiopian women, East African features, varied",
  bolivia: "Bolivian women, Andean and mestizo mix, varied",
  colombia: "Colombian women, Latin American mixed, varied",
  mexico: "Mexican women, Latin American mixed, varied",
  peru: "Peruvian women, Andean and mestizo, varied",
  venezuela: "Venezuelan women, Latin American mixed, varied",
  "dominican-republic": "Dominican women, Caribbean mixed, varied",
  "costa-rica": "Costa Rican women, Latin American mixed, varied",
  india: "Indian women, South Asian features, varied skin tones and hair",
  pakistan: "Pakistani women, South Asian features, varied",
  morocco: "Moroccan women, North African Maghrebi, varied",
  brazil: "Brazilian women, highly diverse mixed ethnicities, varied skin and hair",
  argentina: "Argentine women, Southern European and mestizo mix, varied",
  chile: "Chilean women, Latin American mixed, varied",
  china: "Chinese women, East Asian features, varied",
  mongolia: "Mongolian women, East Asian Central Asian features, varied",
  "south-africa": "South African women, mix of Black, White and Coloured, diverse features",
  russia: "Russian women, Slavic European features, varied hair blonde brown black",
  ukraine: "Ukrainian women, Slavic European features, varied hair",
  poland: "Polish women, Central European features, varied hair",
  romania: "Romanian women, Southeast European features, varied",
  turkey: "Turkish women, Mediterranean and Anatolian, varied",
  kazakhstan: "Kazakh women, Central Asian mixed, varied",
  algeria: "Algerian women, North African Maghrebi, varied",
  libya: "Libyan women, North African, varied",
  usa: "American women, ethnically diverse, varied",
  canada: "Canadian women, ethnically diverse, varied",
  australia: "Australian women, ethnically diverse, varied",
  uk: "British women, ethnically diverse including White British South Asian Black, varied",
  france: "French women, ethnically diverse, European and North African mix, varied",
  germany: "German women, North European features, varied hair blonde brown auburn black",
  spain: "Spanish women, Mediterranean European, varied",
  italy: "Italian women, Mediterranean European, varied",
  sweden: "Swedish women, Nordic features, varied hair blonde light brown",
  japan: "Japanese women, East Asian features, varied",
  "south-korea": "South Korean women, East Asian features, varied",
  "saudi-arabia": "Saudi women, Arabian Peninsula, varied",
  egypt: "Egyptian women, North African Arab, varied",
  iran: "Iranian women, Persian features, varied",
};

export const WOMEN_GROUP_STANDARD_PROMPT_PREFIX =
  "Hyper realistic photograph, 8 women standing in a row side by side, full body visible from head to knees, equal spacing between each person, clean pure white background, even studio lighting, no shadows on background, all women facing camera, neutral friendly expression, women appear 24-26 years old, beautiful as you would see on the street, ";
